// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRBioz62d3ulUrBB6O1-ks4DLz3kSlYQ',
    appId: '1:641001065746:web:85e6ab3ab640274c6f77cb',
    messagingSenderId: '641001065746',
    projectId: 'whatsapp-clone-e9899',
    authDomain: 'whatsapp-clone-e9899.firebaseapp.com',
    storageBucket: 'whatsapp-clone-e9899.firebasestorage.app',
    measurementId: 'G-7YNFLCR121',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbFa7Xl_X6880zaLzAFc8GEAlk2zwZzI8',
    appId: '1:999697171295:android:e15ce5731a9d15a7496cea',
    messagingSenderId: '999697171295',
    projectId: 'whatsapp-efd80',
    storageBucket: 'whatsapp-efd80.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRBioz62d3ulUrBB6O1-ks4DLz3kSlYQ',
    appId: '1:641001065746:web:ae4698e54c48abc36f77cb',
    messagingSenderId: '641001065746',
    projectId: 'whatsapp-clone-e9899',
    authDomain: 'whatsapp-clone-e9899.firebaseapp.com',
    storageBucket: 'whatsapp-clone-e9899.firebasestorage.app',
    measurementId: 'G-68N44RQBQC',
  );
}