// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfK99KzDbBqxugdGPMO9LiU1SFJFYp5-g',
    appId: '1:78644299912:web:9c89a158e039279319373d',
    messagingSenderId: '78644299912',
    projectId: 'flutter-course-a833c',
    authDomain: 'flutter-course-a833c.firebaseapp.com',
    storageBucket: 'flutter-course-a833c.firebasestorage.app',
    measurementId: 'G-RKYQ4WY25P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KVLVEnK6onpzF7HZWyNRFfzagdjFqxI',
    appId: '1:78644299912:android:60408fd092b101e819373d',
    messagingSenderId: '78644299912',
    projectId: 'flutter-course-a833c',
    storageBucket: 'flutter-course-a833c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfK99KzDbBqxugdGPMO9LiU1SFJFYp5-g',
    appId: '1:78644299912:web:59b55e02d1861a6419373d',
    messagingSenderId: '78644299912',
    projectId: 'flutter-course-a833c',
    authDomain: 'flutter-course-a833c.firebaseapp.com',
    storageBucket: 'flutter-course-a833c.firebasestorage.app',
    measurementId: 'G-X6DD1JQEK8',
  );

}