// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD460_aTl94SHlLDQiRNiggXr1MXPlMxiM',
    appId: '1:645394368789:web:cc7f303c6fd07e9faa811c',
    messagingSenderId: '645394368789',
    projectId: 'whats-app-f8576',
    authDomain: 'whats-app-f8576.firebaseapp.com',
    storageBucket: 'whats-app-f8576.firebasestorage.app',
    measurementId: 'G-5877ZP8REX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQADdtOcdZ2olFaGPb8gni307mRWmy3Y',
    appId: '1:645394368789:android:f25734d3ab5d377baa811c',
    messagingSenderId: '645394368789',
    projectId: 'whats-app-f8576',
    storageBucket: 'whats-app-f8576.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD460_aTl94SHlLDQiRNiggXr1MXPlMxiM',
    appId: '1:645394368789:web:d92744ab7ecef844aa811c',
    messagingSenderId: '645394368789',
    projectId: 'whats-app-f8576',
    authDomain: 'whats-app-f8576.firebaseapp.com',
    storageBucket: 'whats-app-f8576.firebasestorage.app',
    measurementId: 'G-BR3S0WPR0P',
  );

}